services:
  reranker:
    build: .
    container_name: reranker
    restart: unless-stopped

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    networks:
      - llm-net

    volumes:
      - hf-cache:/root/.cache/huggingface

    # NESSUNA ports: resta interno

volumes:
  hf-cache:

networks:
  llm-net:
    external: true
